repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
    -   id: ruff-format
    -   id: ruff

-   repo: https://github.com/numpy/numpydoc
    rev: v1.7.0
    hooks:
    -   id: numpydoc-validation
        files: ^src/
