name: Tests

on:
  push:
    branches: ['**']
    tags-ignore: ['*']

jobs:
  tests:
    name: Run tests

    if: ${{ ! contains(github.event.head_commit.message, 'Merge pull request') }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        py: ['3.10', '3.11', '3.12', '3.13']
      fail-fast: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: (Linux) Get latest commit SHA of main branch
        if: runner.os == 'Linux'
        run: |
          git fetch origin main
          MAIN_SHA=$(git rev-parse origin/main)
          echo "main_sha=$MAIN_SHA" >> $GITHUB_ENV

      - name: (Windows) Get latest commit SHA of main branch
        if: runner.os == 'Windows'
        run: |
          git fetch origin main
          $MAIN_SHA = git rev-parse origin/main
          Add-Content -Path $env:GITHUB_ENV -Value "main_sha=$MAIN_SHA"

      - name: Check for changed python files
        id: changed-py-files
        uses: tj-actions/changed-files@v44
        with:
          base_sha: ${{ env.main_sha }}
          files: '**/*.py'

      - name: Setup python
        if: steps.changed-py-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
          cache: 'pip'

      - name: Install tox and its GitHub action plugin
        if: steps.changed-py-files.outputs.any_changed == 'true'
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox "tox-gh>=1.2"

      - name: Setup tox environments
        if: steps.changed-py-files.outputs.any_changed == 'true'
        run: tox --notest

      - name: Run test suite
        if: steps.changed-py-files.outputs.any_changed == 'true'
        run: tox --skip-pkg-install
